#!/usr/bin/env bash
set -eo pipefail

export WORKING_DIR="processing"
export PATCH_DIR="patches"
export TARGET_FILE="template.yaml"

export SSH_KEY_NAME="terraform"
export HCLOUD_REGION="fsn1"
export HCLOUD_CONTROL_PLANE_MACHINE_TYPE="cx22"
export HCLOUD_WORKER_MACHINE_TYPE="cx22"

rm -rf ${WORKING_DIR}
mkdir -p ${WORKING_DIR}

clusterctl generate cluster dummy \
    --infrastructure hetzner:v1.0.6 \
    --target-namespace cluster-dummy \
    --kubernetes-version v100.0.0 \
    --control-plane-machine-count=3 \
    --worker-machine-count=1 \
    >| ${WORKING_DIR}/dummy.yaml

kubectl slice -f ${WORKING_DIR}/dummy.yaml -o ${WORKING_DIR}/
rm -f ${WORKING_DIR}/dummy.yaml

rm -f ${WORKING_DIR}/hcloudmachinetemplate-dummy-control-plane.yaml
rm -f ${WORKING_DIR}/hcloudremediationtemplate-control-plane-remediation-request.yaml
rm -f ${WORKING_DIR}/kubeadmcontrolplane-dummy-control-plane.yaml
rm -f ${WORKING_DIR}/machinehealthcheck-dummy-control-plane-unhealthy-5m.yaml
rm -f ${WORKING_DIR}/kubeadmconfigtemplate-dummy-md-0.yaml

mv ${WORKING_DIR}/cluster-dummy.yaml ${WORKING_DIR}/cluster.yaml
mv ${WORKING_DIR}/hetznercluster-dummy.yaml ${WORKING_DIR}/hetznercluster.yaml
mv ${WORKING_DIR}/machinehealthcheck-dummy-md-0-unhealthy-5m.yaml ${WORKING_DIR}/machinehealthcheck-worker-unhealthy-5m.yaml
mv ${WORKING_DIR}/hcloudmachinetemplate-dummy-md-0.yaml ${WORKING_DIR}/hcloudmachinetemplate-worker.yaml
mv ${WORKING_DIR}/machinedeployment-dummy-md-0.yaml ${WORKING_DIR}/machinedeployment-fsn1.yaml

cat << 'EOF' > ${WORKING_DIR}/k0smotroncontrolplane.yaml
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: v100.0.0-k0s.0
  persistence:
    type: emptyDir
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132
    annotations:
      external-dns.alpha.kubernetes.io/ttl: "1"
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
      load-balancer.hetzner.cloud/type: "lb11"
      load-balancer.hetzner.cloud/network-zone: "eu-central"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      controllerManager:
        extraArgs:
          cloud-provider: external
      network:
        provider: custom
        podCIDR: 10.244.0.0/16
        serviceCIDR: 10.96.0.0/12
      telemetry:
        enabled: false
  monitoring:
    enabled: true

...
EOF

cat << 'EOF' > ${WORKING_DIR}/k0sworkerconfig.yaml
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: ${CLUSTER_NAME}
spec:
  template:
    spec:
      version: v100.0.0+k0s.0
      args:
        - --kubelet-extra-args="--cloud-provider=external --node-ip=$(ip -4 -o addr show scope global | grep -vE 'cali|tunl|wireguard' | awk '{print $4}' | cut -d/ -f1 | grep -m1 -E '^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)')"
      files:
        - path: /etc/modules-load.d/crio.conf
          owner: root:root
          permissions: "0744"
          content: |
            overlay
            br_netfilter
        - path: /etc/sysctl.d/99-kubernetes.conf
          owner: root:root
          permissions: "0744"
          content: |-
            net.bridge.bridge-nf-call-iptables = 1
            net.bridge.bridge-nf-call-ip6tables = 1
            net.ipv4.ip_forward = 1
            net.ipv6.conf.all.forwarding = 1
            net.ipv6.conf.all.accept_ra = 0
            net.ipv6.conf.default.accept_ra = 0
        - path: /etc/sysctl.d/99-kubelet.conf
          owner: root:root
          permissions: "0744"
          content: |-
            vm.overcommit_memory=1
            kernel.panic=10
            kernel.panic_on_oops=1
        - path: /etc/sysctl.d/99-fsnotify.conf
          owner: root:root
          permissions: "0744"
          content: |-
            fs.inotify.max_user_instances = 8192
            fs.inotify.max_user_watches = 1048576
            fs.inotify.max_queued_events = 65536
        - path: /etc/apt/apt.conf.d/50unattended-upgrades
          owner: root:root
          permissions: "0744"
          content: |-
            Unattended-Upgrade::DevRelease "false";
            Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
            Unattended-Upgrade::Remove-Unused-Dependencies "true";
            Unattended-Upgrade::Automatic-Reboot "false";
            Unattended-Upgrade::SyslogEnable "true";
            Unattended-Upgrade::SyslogFacility "daemon";
            Unattended-Upgrade::Allowed-Origins {
              "$${distro_id}:$${distro_codename}";
              "$${distro_id}:$${distro_codename}-security";
              "$${distro_id}:$${distro_codename}-updates";
              "$${distro_id}:$${distro_codename}-proposed";
              "$${distro_id}:$${distro_codename}-backports";
              "$${distro_id}ESMApps:$${distro_codename}-apps-security";
              "$${distro_id}ESM:$${distro_codename}-infra-security";
            };
      preStartCommands:
        - modprobe overlay && modprobe br_netfilter && sysctl --system
        - install -d -m 755 -o root -g root /var/lib/kubelet/plugins_registry

...
EOF

for FILE in ${WORKING_DIR}/*.yaml; do
    for PATCH in ${PATCH_DIR}/$(basename ${FILE} .yaml); do
        if test -f "${PATCH}.json"; then
            echo "Applying ${PATCH}.json"
            cat "${FILE}" \
                | yq -o json eval \
                | json-patch --patch-file=${PATCH}.json \
                | yq -P eval - \
                >| ${FILE}.temp

            mv ${FILE}.temp ${FILE} && rm -f ${FILE}.temp
        fi
    done

    yamlfmt "${FILE}"

    sed -i '1i ---' "${FILE}"
    echo >> "${FILE}"
    echo "..." >> "${FILE}"
done

cp ${WORKING_DIR}/machinedeployment-fsn1.yaml ${WORKING_DIR}/machinedeployment-nbg1.yaml
sed -i 's/fsn1/nbg1/g' ${WORKING_DIR}/machinedeployment-nbg1.yaml

cp ${WORKING_DIR}/machinedeployment-fsn1.yaml ${WORKING_DIR}/machinedeployment-hel1.yaml
sed -i 's/fsn1/hel1/g' ${WORKING_DIR}/machinedeployment-hel1.yaml

cat << 'EOF' > ${WORKING_DIR}/resourcesets.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-${CLUSTER_NAME}-oidc
data:
  cluster-${CLUSTER_NAME}-oidc.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: oidc:cluster-${CLUSTER_NAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: oidc:cluster-${CLUSTER_NAME}

...
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cluster-${CLUSTER_NAME}-oidc
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      cluster: ${CLUSTER_NAME}
  resources:
    - name: cluster-${CLUSTER_NAME}-oidc
      kind: ConfigMap

...
EOF

cat ${WORKING_DIR}/*.yaml >| ${TARGET_FILE}
sed -i 's|v100.0.0|${KUBERNETES_VERSION}|' ${TARGET_FILE}
rm -rf ${WORKING_DIR}
